### ISSUE TITLE
Calculation issue

### ISSUE THREAD

**Issue by alienatedsec** [jevburchell/Solis-Modbus-Auto-Charging-using-Solax#11]
Hi @jevburchell 

I am struggling to understand the calculation - my battery is about 60% now, and it will discharge by the morning. Despite both `SoC at the Start` of Offpeak and `SoC at the End of Offpeak` show values below Overdischarge (15%) and Forcharge SoC (12%) , it still shows that not required to charge.

It will start using the grid when hitting `1.50` kWh so not sure if it should show `Charge Scheduled`(?)

![image](https://github.com/jevburchell/Solis-Modbus-Auto-Charging-using-Solax/assets/73167064/5743261e-c2fd-4af9-b5c7-3892d42f874c)

Is that usable `SoC at the End of Offpeak`? or what the battery will have?
I would appreciate any help :)

**Comment by jevburchell** [comment]
Evening,

Is your battery storage capacity around 10kWh?

The remaining SoC at the end of the offpeak period [highlighted] is a
measure of usable charge above your overdischarge SoC.  So if you have 1kWh
left at 5am, and a base load of 400W, you'll be good to 7:30am until the
sun is up.  However as its close you could always add on a kWh of boost
charge to see you through :)

Make sense?

**Comment by alienatedsec** [comment]
> Is your battery storage capacity around 10kWh?

Correct

> So if you have 1kWh left at 5am, and a base load of 400W, you'll be good to 7:30am until the sun is up.

It makes sense, but changing it to 1kW baseload is not making any difference
![image](https://github.com/jevburchell/Solis-Modbus-Auto-Charging-using-Solax/assets/73167064/5845f12f-1c17-42cf-a6e6-865b70b09afc)

**Comment by jevburchell** [comment]
Yes, this is a feature which is there by design, but perhaps does require
some tweaking.  Let me explain:

What you are seeing is the algorithm deciding that it will get through
tomorrow without charging tonight.  This is because the Solcast forecast
for tomorrow exceeds your expected usage for tomorrow.  (Solcast tomorrow =
20.37kWh, expected usage = 13kWh, therefore surplus = around 7kWh).  What
the algorithm is doing is saying ok, there will be a small (or zero) amount
of charge left at the end of tonight, but because there will be surplus
solar production tomorrow, a charge is not required because the batteries
will be replenished from solar yield tomorrow.

What this does not cater for, and is an area for me to improve, is the gap
between the end of the offpeak period tonight, and the sun rising.  As we
get further away from the summer solstice, this becomes a longer duration,
and I had added the “boost charge” function to cater for this, but perhaps
it is something which should be further automated.  As this algorithm was
developed in summer, this is something I was aware of as possibly being an
area to develop further, and thank you for bringing it to my attention now.

My thoughts on options are:

1. Set a minimum value for the SoC at end of offpeak period tonight.  This
could be 2kWh for example, and if the algorithm forecasts that it will drop
below this it could add a preset charge value.

2. Develop a function which calculates the time between the end of the
offpeak period and sunrise, and multiply this by the base load to calculate
the minimum SoC at end of offpeak period.  If the SoC is less than this
minimum value, it could be added to the charge value.  (Slightly more
complex).

3. Leave it as is, and manage using the existing boost charge function.

Do you have any thoughts or ideas?

Thanks for your input!

**Comment by alienatedsec** [comment]
> 3. Leave it as is, and manage using the existing boost charge function.

@jevburchell I am certain that amending the boost charge function (at least last night) has made no difference and the status remained unchanged - in fact, amending it now is the same.

<img width="252" alt="image" src="https://github.com/jevburchell/Solis-Modbus-Auto-Charging-using-Solax/assets/73167064/b5bb2b3d-0920-497f-8eec-c1d1dab53b07">

In addition, option 3 is making the whole 'automation' not automated. 

> 2. Develop a function which calculates the time between the end of the
offpeak period and sunrise, and multiply this by the base load to calculate
the minimum SoC at end of offpeak period.  If the SoC is less than this
minimum value, it could be added to the charge value.  (Slightly more
complex).

Option 2 seems reasonable with the below caveat(?):
- The sunrise needs to include the expected generation to cover the baseload - unless unknown or we don't really care(?)
- Any other considerations?

**Comment by jevburchell** [comment]
Couple of things,

Boost charge is separate from auto charge.  So applying boost charge will
set a charge time of whatever you set regardless of what the auto charge
function decides.  I see with it at 10kWh there you have 8.8kWh showing at
the end of each offpeak period - which makes sense for your setup with
Forcecharge SoC set at 12% with 10kWh of storage.  The figures are all the
same due to being maxed out.

So setting boost charge as in option 3 does still leave the system
automated - you're just choosing to feed in more grid charge for whatever
reason you choose.

I'll need to ponder option 2 a bit more, as it's possible to inadvertently
produce a calculation loop which would be undesirable..
