### ISSUE TITLE
Missing Sensors?

### ISSUE THREAD

**Issue by n8091977** [jevburchell/Solis-Modbus-Auto-Charging-using-Solax#12]
Hello,

Could you advise where the following sensors are defined? I'm struggling to understand how to adapt your great work for Octopus Intelligent.

Thanks,
James

sensor.octopus_flux_tariff_offpeak
sensor.octopus_flux_tariff_peak
sensor.octopus_flux_tariff_flux

**Comment by jevburchell** [comment]
Apologies,

These sensors are not used in these releases and are leftovers from my own instance of this project (which this code is derived from).

These sensors are used on my system to calculate real-time daily costs of electricity import on the octopus flux tariff.  These are then displayed on the dashboard: 

![Screenshot_20230802_180718_Home Assistant](https://github.com/jevburchell/Solis-Modbus-Auto-Charging-using-Solax/assets/128035411/807f5d58-e2fb-477d-a63f-5d0acbf740df)

- To alter the code to fit octopus intelligent is straightforward.  In Solax, change the timed charge 1 times to match the start of your offpeak period.  
- Then change the "Offpk Window" helper to match the duration of your offpeak period.  
- As OI starts at 2330, you'll also need to alter the "Solar - Battery Charge Automation" to fire at 23:25 rather than 23:55.

Kind regards

**Comment by n8091977** [comment]
Ah thanks so much, so it simply uses battery automation to trugger the start and the Offpeak Window to derive the duration?

And I can delete those sensors above form the template, great - thanks so much.

**Comment by jevburchell** [comment]
Yes :)

Any issues implementing just let me know

**Comment by n8091977** [comment]
Could you kindly advise on the below from the docs - manually set in SOLAX Integration - where? I assume this is UTC. But even at that seem smy charge will start at 23:00 and run for 01:32 mins until 00:32 and thus charge before IO.

![image](https://github.com/jevburchell/Solis-Modbus-Auto-Charging-using-Solax/assets/6561929/c2da9286-bc0d-4f4b-a34e-99f2a6b295aa)

![image](https://github.com/jevburchell/Solis-Modbus-Auto-Charging-using-Solax/assets/6561929/ee3e0ac4-ec91-41d6-ab43-5cb8b56d39cf)

**Comment by jevburchell** [comment]
Settings > Devices & services > Solax Inverter Modbus.

The entity is number.solax_timed_charge_start_hours

**Comment by jevburchell** [comment]
Apologies, additionally you'll need to update number.solax_timed_charge_start_minutes to "30"
